### ISSUE TITLE
Request for a broken heart glyph to match the regular heart glyph

### ISSUE THREAD

**Issue by DanisDGK** [slavfox/Cozette#102]
I generally use the heart and broken heart glyphs in my prompt to visualize zero or non-zero exit codes, but since this font doesn't have a broken heart glyph, I am using this instead.
![image](https://github.com/slavfox/Cozette/assets/38492793/0bf32aa9-4378-485e-81bd-6499e6be7c81)
![image](https://github.com/slavfox/Cozette/assets/38492793/46db638e-8aed-4fd0-a4a8-1a627c24a96d)
Would be nice to have a broken heart glyph that fits the heart I'm using for success.

**Comment by slavfox** [comment]
I keep trying to find a way to do this, but it turns out, against all expectations, that... adding a useful broken heart glyph to a bitmap font is a much more complex problem than it might initially seem.

Unicode, to my surprise, *only* has one broken heart symbol in it: :broken_heart:. The problem with that is :broken_heart: is an emoji and renders as double-width in most applications:
```
123456789
123💔56789
```

So if I were to add a :broken_heart: it'd have to be double-width to render nicely, which would mean you'd get a small, single-width `♥` and a massive double-wide :broken_heart:; not ideal for a prompt. Okay, so clearly I should add :heart: as well, right?

Unfortunately, Unicode and emoji are a mess, and :heart: is *not* actually an emoji codepoint - it has existed prior to emoji, as U+2265 BLACK HEART SUIT, a "normal" character. This means that depending on the application (and sometimes even within the same application, as I'll show in a second) `♥` renders as *either* single-width or double-width, so for compatibility, I'd have to make it single-width. Even Github renders that character as a single-wide "normal" character if in a code block:
```
123456789
123♥56789
```
But as a double-wide emoji in other contexts:

123456789
123♥56789

I'm going to have to consider this for a bit and decide whether I want to, perhaps, use a PUA codepoint for a bespoke single-width broken heart character.

**Comment by DanisDGK** [comment]
That is indeed quite unfortunate, no worries though, take your time. I can deal with it by just doing what I'm doing already.

**Comment by slavfox** [comment]
I found a single-width broken heart in [Material Design Icons](https://pictogrammers.com/library/mdi/icon/heart-broken/) at U+F02D4, but... I'm really unhappy with how a single width broken heart looks at Cozette's size:
![image](https://github.com/slavfox/Cozette/assets/35173529/0668190c-cbae-48ad-b825-c0672eb89921)

I have, nevertheless, added it to Cozette and will push a new minor version soon.

**Comment by slavfox** [comment]
[v.1.22.0](https://github.com/slavfox/Cozette/releases/tag/v.1.22.0) has matching heart glyphs at:

`󰋑` (U+F02D1, full heart)
`󰋔` (U+F02D4, broken heart)
