### ISSUE TITLE
Some Vietnamese characters aren't align/look correct.

### ISSUE THREAD

**Issue by NNBnh** [slavfox/Cozette#110]
| Current characters | What it's should look like |
| - | - |
| ![font_current](https://github.com/slavfox/Cozette/assets/43980777/e295eaf8-7120-475a-b6c2-f8ceb69a247c) | ![font_true](https://github.com/slavfox/Cozette/assets/43980777/909b0b20-0694-48ca-829e-bdfe1dabbdd5) |

> **Note** _"Current characters"_ is using `CozetteVector.otf` release `v.1.22.2` in Godot 4.1.

![font_check](https://github.com/slavfox/Cozette/assets/43980777/6fb9e6cc-061c-44a0-8eba-d0ab1fb776ca)

[Vietnamese font test](https://codeberg.org/NNB/vietnamese_font_test)

**Comment by slavfox** [comment]
Running through these right now so I have this handy later when I get to fixing the font.

definitely need to be fixed:
- `Ễễ`, missing diacritics
- `Ưư` and similar, the horn is not a hook

need to verify:
- `ả` etc, might need to raise the hook by a pixel if it will fit other characters
- `Ẳẳ` etc, the hook probably shouldn't be offset and `Ẳ` might need to go below the baseline
- `Ẵẵ` etc - I'm assuming reference fonts for Cozette had the breve drawn above the tilde, need to check how other fonts do it and which way is more common

unsure:
- `Ơơ`, the placement of the horn depends on font

Characters that won't be changed:

wontfix, have to be this way because of vertical space restrictions (Cozette only has 10px to work with above the baseline):
- `ÃãÓóÒòỎỏÕõ` etc etc etc
- `Ẫ` etc, they need to go below the baseline to fit the extra diacritics

wontfix,
![image](https://github.com/slavfox/Cozette/assets/35173529/5a58ceb6-05e2-4bc6-857d-f846f5138f12)
is already used for a caron:
- `Ăă` etc

wontfix, these match how they look in reference fonts:
- `ỐốỒồỔổ` etc

**Comment by slavfox** [comment]
Hopefully I'll have time to get to fixing these this week.
