### ISSUE TITLE
Contrib: Windows Bitmap Font

### ISSUE THREAD

**Issue by oxou** [slavfox/Cozette#123]
I've converted the .FNT format to .FON which Windows can recognize.  You can include it in your next release.
[cozette.fon.zip](https://github.com/slavfox/Cozette/files/14541991/cozette.fon.zip)

**\*** Albeit the nerd font glyphs are not present because of the inherent limitation of FON files.

![image](https://github.com/slavfox/Cozette/assets/102489121/f39496d2-1a84-4047-8c78-f4d609e748a4)
![image](https://github.com/slavfox/Cozette/assets/102489121/9af2d9f9-e846-4450-a7ae-506a04e8cb5f)

---

Maybe I'll add a PSF version for the Linux console too (as mentioned by someone in #122) - but until that happens I must rewrite [bdf2psf](https://manpages.debian.org/testing/bdf2psf/bdf2psf.1.en.html) in a more sane language.

**Comment by slavfox** [comment]
A single build is not useful for this repository. This should be either integrated into the build scripts so that it gets built on every fresh release, or otherwise - if it's too specific a usecase - left to users to convert on their own, search engines bring up plenty of ways to convert other formats to .FON.
