### ISSUE TITLE
Windows doesn't recognize CozetteVector.ttf as a monospace font

### ISSUE THREAD

**Issue by wfraser** [slavfox/Cozette#14]
Some programs (i.e. PuTTY) filter the list of fonts to only monospace ones by default, and Cozette isn't showing up in that set. In PuTTY if I enable "Allow selection of variable-pitch fonts" then it shows up. Other programs like PowerShell don't let you select non-monospaced fonts at all, so it's impossible to use there.

Must be some monospace bit that can be set in the font metadata?

**Comment by slavfox** [comment]
Oh, this sounds interesting to try and tackle. I'll see what I can do, although I don't have a Windows machine handy; [this looks somewhat promising](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#hmtx-table).

**Comment by slavfox** [comment]
Based on what I can see in the source, PuTTY finds monospace fonts by checking textmetrics with wingdi.h; `tmPitchAndFamily` is the [relevant value here](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-textmetrica).

I forgot that this is Microsoft-land, though, and so that I won't find the source code for that function. How do people even get work done on Windows? :sweat_smile: 

Regardless, I'll try filling out the relevant tables mentioned in my previous comment, and see what happens.

**Comment by slavfox** [comment]
It's not looking like I can fix this atm. I don't have a Windows partition handy, the documentation on both Windows font shenanigans and fonttools is extremely scarce, and I find it very difficult to try and figure out what's going wrong. If someone's willing to pick it up, the solution will _probably_ involve setting up another table in [ttfbuilder.py](https://github.com/slavfox/Cozette/blob/master/cozette_builder/ttfbuilder.py#L91) - the relevant fonttools sources are [here](https://github.com/fonttools/fonttools/blob/51bff6cf6a08976c831aa5c9e8c901fac7e61dea/Lib/fontTools/fontBuilder.py), since it doesn't really have useful docs.

**Comment by ym1234** [comment]
```
A TrueType font can contain a post table. The post table contains a 32-bit field named isFixedPitch. If this contains a 0, it indicates a proportional font. A monospaced font should have this set to 1 (but its normally recommended that a font engine should accept any non-zero value as indicating a monospaced font, since that's what early versions of the TT spec required).

A monospaced font should also have the numberOfHMetrics in the hhea and hmtx tables set to 3.

There's also data in the panose font matching data (in the OS/2 table) to specify whether a font is monospaced or not.

If I had to guess, I'd say Apple is more likely to use the post table, while Microsoft is more likely to use the Panose data (but I could easily be wrong about either or both of those).

References:

Apple documentation of 'post' table
Microsoft OpenType Recommendations
Panose Classification Metrics Guide
```
From [StackOverFlow](https://stackoverflow.com/a/43178653)
Looking at [Font tools line 188](https://github.com/fonttools/fonttools/blob/51bff6cf6a08976c831aa5c9e8c901fac7e61dea/Lib/fontTools/fontBuilder.py#L188) the default is variable width and ttfbuilder.py doesn't change it to 1 when setupPost is called

**Comment by slavfox** [comment]
I don't know why this didn't occur to me earlier, I'd seen that exact post before and somehow completely missed the point. Thank you for pointing this out @ym1234, I've added a note crediting you at the bottom of the README.

@wfraser could you try [release 1.8.1](https://github.com/slavfox/Cozette/releases/tag/v.1.8.1) and see if that fixed the problem?

**Comment by wfraser** [comment]
Yeah, that worked great! Thanks @slavfox & @ym1234 !
