### ISSUE TITLE
Add "intended size" to README

### ISSUE THREAD

**Issue by jsejcksn** [slavfox/Cozette#17]
> Bitmap fonts are, effectively, just that - bitmaps. They scale terribly, but look nice and sharp (and pixel-perfect) **if you use them at their intended point size**. Vector fonts scale well, but in this case, might look ugly at smaller point sizes because of antialiasing issues and the like.

What is the "intended point size"?

**Comment by slavfox** [comment]
The one at which it looks sharp. The exact meaning seems to differ between operating systems, graphical backends, font rendering libraries, displays, etc - it's 13 points on my Macbook, and 8-10 points on Linux with Pango, at least for me. I've gotten reports that it can be different on other Macbook models with different screens, and I've heard of at least one Linux system where the font looked correct at a different point size as well.

Since font metrics are a bit black magicky and up to the implementation to handle, it's infeasible for me to test every possible configuration to keep the README up to date, whereas for a user trying to find a point size at which the font looks correct it's just a matter of scrolling through the font sizes in the GUI until it looks sharp.

**Comment by jsejcksn** [comment]
Thanks for responding. I think I might not have communicated clearly. Without a background in typography, some people will find this recommendation without a prescription confusing. Maybe you can provide some quantitative information so that those interested can get the intended settings.

For example, you could provide the pixel dimensions of a few particular ASCII glyphs, so they could be measured during a font-scaling test.

**Comment by slavfox** [comment]
Apologies! It didn't occur to me to think about the pixel dimensions because... I was convinced they already were part of the README :sweat_smile: 

I've added a note about them. Thanks for suggesting this change.
