### ISSUE TITLE
Bold Variant

### ISSUE THREAD

**Issue by 0xdhrv** [slavfox/Cozette#20]
I have faced a few issues with bold characters like letter m. The problem is that the character becomes so thick that it's difficult to identify them. I have seen this for all the characters, the only problem is with only letter m (small one). I have attached one the screenshot for understanding. Thanks, it's an amazing font and cozy as well.

**Comment by TheAvidDev** [comment]
Just a heads up, I don't see any screenshot attached. Perhaps you should try again?

**Comment by 0xdhrv** [comment]
Here's a screenshot 
![upload](https://user-images.githubusercontent.com/19857414/83939402-518bcb00-a7fa-11ea-92b8-a14dc7255734.png)

**Comment by slavfox** [comment]
As much as I'd like to, this isn't really possible for me to work around _easily_ - glyphs in bitmap fonts are bolded by the terminal, by redrawing the glyph one pixel to the right, like this: 
![image](https://user-images.githubusercontent.com/35173529/83956744-8717cf00-a861-11ea-8ea4-87aab769ae77.png)
 
Since Cozette is a 6px wide font, with 5px for the actual character (and 1px for the space), there isn't really a way to draw lowercase `m` with wider spacing between the legs than the current one: `#.#.#`, for five pixels wide.

The solution for this would be to make a bold variant of the font, and let fontconfig handle switching to Cozette-Bold for bold glyphs. This is quite a bit of work, due to the sheer number of glyphs that would need redrawing for the bold variant - and `m` is far from the most problematic one. The cyrillic block, in particular, would be an absolute mess with some of these glyphs: 
![image](https://user-images.githubusercontent.com/35173529/83956890-bda21980-a862-11ea-9a60-8fc3a514dabb.png)

A bold variant is on the roadmap, but unlikely to happen anytime soon.

**Comment by 0xdhrv** [comment]
Pretty Detailed Reply! I already thought about the bold variant, the font itself is so good that I am using it as my default font in the terminal, and sometimes, in various scripts, the bold variant by the terminal, kinda looks awful specifically for the letter "m". Now, knowing what are the issues with letter "m", I'll try to not use the bold in any of the terminal.
