### ISSUE TITLE
dual licensing request

### ISSUE THREAD

**Issue by r-lyeh** [slavfox/Cozette#25]
Hey @slavfox 

First of all, great job with the font. I really like it.

Second, a suggestion, a MIT licensed open source font seems a bit odd choice to me, as even when embedding the fonts in a document would require users to supply the MIT license terms besides their own document. Most open-source fonts utilize the Open Font License (or OFL) by SIL international instead. Check https://en.wikipedia.org/wiki/SIL_Open_Font_License for further details. I'd suggest you to go with dual licensing: MIT or SIL, and let the end-user choose whichever license s/he prefers :D

Anyways, good work you did there!
Keep it up!

**Comment by slavfox** [comment]
That's an excellent idea! I considered SIL initially, but decided to go for MIT out of respect for Cozette's biggest inspirations - Dina, Proggy, and creep, all of which are MIT - it never occured to me to dual-license it. I'm currently redoing the build system; the next release will have a dual license.

**Comment by slavfox** [comment]
Sorry for taking such a long time to do this, I've been pretty busy lately. I just realized this might not be such a good idea after all, because the OFL, afaict, doesn't actually help you in any way in this case:

(SIL OFL 1.1)
> PERMISSION & CONDITIONS
> Permission is hereby granted, free of charge, to any person obtaining
> a copy of the Font Software, to use, study, copy, merge, embed, modify,
> redistribute, and sell modified and unmodified copies of the Font
> Software, subject to the following conditions:
> [...]
> 2) Original or Modified Versions of the Font Software may be bundled,
> redistributed and/or sold with any software, **provided that each copy**
> **contains the above copyright notice and this license.** These can be
> included either as stand-alone text files, human-readable headers or
> in the appropriate machine-readable metadata fields within text or
> binary files as long as those fields can be easily viewed by the user.
> [...]

Since that clause removes any benefit of dual-licensing, I'd rather keep the terms simpler and stick with MIT.
IANAL, feel free to reopen if I've misunderstood the above clause.

**Comment by r-lyeh** [comment]
It states that the truetype may (not must) be distributed with any software. It is optional.
Then, when distributed, whoever does the Font distribution must add the LICENSE file besides it. Same as MIT.
It is not referring to the Works that you may do with the Font.

**Comment by slavfox** [comment]
Thinking out loud, just so that we can make sure we're on the same page, and if not, find the source of disagreement:

- If used in eg. artwork, both licenses place no obligations on its creator. OFL explicitly states that no attribution is required, and a "derived graphic or object" (eg. a screenshot of the font) does not, AFAICT, constitute a "copy or substantial portion of the software" any more than the text "Hello, World!" constitutes a copy of a hello world program when it comes to MIT. Both licenses are effectively equivalent in this usecase.
- OFL prevents you from selling the font standalone.
- MIT explictly allows sublicensing, while OFL explicitly forbids it.
- When distributing the font, both licenses require you to retain the copyright notice and license text.
- OFL has a muddy exception that allows you to omit the attribution if the font is part of the document (embedded) as opposed to distributed alongside it.

My understanding is this:

|  | MIT  | OFL |
| ------ | ------ | ------ |
| Distribution of the compiled fonts or derivatives  | :heavy_check_mark: requires attribution | :heavy_check_mark: requires attribution |
| Embedding | :heavy_check_mark: is not a "copy of the software", no attribution required | :heavy_check_mark: is a "document created using the Font Software", no attribution required |
| Distribution of the build scripts or derivatives | :heavy_check_mark: requires attribution | :x: would need a different license for code |
| Selling the font | :heavy_check_mark: ok | :x: only if part of a package with literally anything else |
| Sublicensing | :heavy_check_mark: ok | :x: ? |

As far as I can tell, the MIT license places strictly less restrictions on the usage of the font, and so I don't feel it'd make sense to dual-license with OFL, a more restrictive license. Does that make sense/did I miss anything?
