### ISSUE TITLE
U+F4BE, U+F631, U+FD52 are not present in `.sfd` but are listed in the changelog

### ISSUE THREAD

**Issue by cpkio** [slavfox/Cozette#72]
The title says it all :)

**Comment by slavfox** [comment]
Hm... This is bizarre.

First of all, thanks for noticing - I have no idea how this happened, since I use a script to generate the changelogs.
Second, I removed two of those glyphs from the changelog and added the third to the font, but now I cannot generate the example images - `xterm -fa Cozette` says `xterm: Selected font has no non-zero height for ISO-8859-1 encoding` and quits. The font seems to work fine outside of xterm, but I'm reluctant to push a new update until I figure out this issue.

**Comment by slavfox** [comment]
Can you verify whether this build of cozette.otb works with xterm on your machine?
[cozette.otb.zip](https://github.com/slavfox/Cozette/files/9379939/cozette.otb.zip)

**Comment by slavfox** [comment]
Nevermind, I redid my changes from scratch and it works now. Fixed in v.1.16.0!

**Comment by cpkio** [comment]
I thought this project was abandoned so I had to make my own fork. I've added a few new glyphs and made some changes (look at the fractions for example, I think they're readable and look awesome in text). I would gladly merge my work into yours, but `.sfd` is not sorted by glyph unicode point number, so diffing them is a pain. If you could find a way to sanely sort'n'diff .sfd's, that would be awesome.

![showcase](https://user-images.githubusercontent.com/1917113/185732126-d3bcd391-07b5-48b1-91f6-eed915f419ef.png)

**Comment by slavfox** [comment]
The difficulty in diffing was a big part of why it was so hard for me to continue work on this 😔 I may have a better solution for this in the future.
