### ISSUE TITLE
Zutty Terminal support

### ISSUE THREAD

**Issue by ZeusThundr** [slavfox/Cozette#82]
Can't seem to make it work on [Zutty](https://github.com/tomscii/zutty) it keeps telling me 
>  No suitable files for 'cozette' found!

I've tried to to symlink the name of the file to another name as suggested in the [user guide](https://tomscii.sig7.se/zutty/doc/USAGE.html#Making%20fonts%20discoverable)
Sorry for my ignorance it's probably something very simple that I am missing.
I've tried the fonts in fonts.alias in my `/usr/share/fonts/misc/fonts.alias` all the fonts listed in that file work It must be the way I am formatting the name wrong. The fonts that work their names look like this `-misc-fixed-medium-r-normal--7-70-75-75-c-50-iso8859-1`
EDIT: The dev of zutty was kind enough to let me know it is the file format of the font sorry for the issue. The terminal only currently supports ttf, otf and pcf.gz. Any tips on how to get started converting the font for layman like my self?
EDIT2: there is an aur package that named nerd-fonts-cozette-ttf which does work but the letter spacing is off and doesn't look as crisp as alacritty or other terminals and it slightly larger. Close but no cigar. Feel free to close this I'll just switch to a different terminal.

**Comment by slavfox** [comment]
Apologies for the late response. `Zutty` seems to only support bitmap fonts in `PCF` format. FontForge, which I'm using to build Cozette, doesn't support PCF output. A quick Google search brings up https://linux.die.net/man/1/bdftopcf as a way to get a PCF font from a BDF.

**Comment by JobLeonard** [comment]
In case anyone ran into this (a need for a `pcf` version) and for whatever reason doesn't have `bdftopcf` installed: there's also an online version of the converter hosted by adafruit (since their circuitpython stuff also prefers PCF over BDF)

https://adafruit.github.io/web-bdftopcf/

But the conversion doesn't seem to go quite right, the baseline is all over the place:

![Image](https://github.com/user-attachments/assets/4fa68e92-591d-4c2b-bcb8-0bc96ab07700)

I've tried both web and CLI versions of `bdftopcf`, and all possible settings. Could the issue be in the way FontForge handles bounding boxes with bitmap fonts? Because I found [this reddit thread on vertically centering glyphs](https://old.reddit.com/r/FontForge/comments/11r6x4q/vertically_centering_glyphs/) that seemed somewhat related.

Anyway, the grumpy Zutty FAQ entry on this makes me a lot less interested in trying it so meh. Just sharing information here to give others a head-start if they feel like giving it a shot
