### ISSUE TITLE
cozette.fnt does not work on a linux console

### ISSUE THREAD

**Issue by wfrsk** [slavfox/Cozette#83]
Using Arch Linux

```sh
# cp ~/downloads/cozette.fnt /usr/share/kbd/consolefonts
# setfont /usr/share/kbd/consolefonts/cozette.fnt
setfont: ERROR setfont.c:527 kfont_load_font: Bad input file size
```

**Comment by slavfox** [comment]
`.fnt` is a Windows font format. `setfont` loads `psf` fonts, which FontForge does not support as an output format. Since Cozette is built in FontForge, this will not be fixed. 

A quick Google search brought up http://www.seasip.info/Unix/PSF/index.html as a possible way to convert one of the Cozette versions to PSF, but I cannot vouch for whether it works.

**Comment by immjs** [comment]
Hi, sorry for necro-bumping, I just wanted to say psftools's `fnt2psf` did the trick for me, *although* it will only work if you use `--psf1`, which I assume is the version that Linux's vconsole supports? (that would explain why the `cozette.psf` in Releases doesn't work)
