### ISSUE TITLE
Tag zipped fonts with version

### ISSUE THREAD

**Issue by slavfox** [slavfox/Cozette#98]
Just noticed @twelveeighty mention this causes issues for AUR packaging, hopefully this makes their life easier.

**Comment by twelveeighty** [comment]
@slavfox I'm not that familiar with HiDPI stuff, can you clarify something for me: with the latest release version being "1.19.2-hidpi" instead of "1.19.3", does this mean we will have two release chains going forward: one with and one without the 'hidpi' subtag? So the next release will be both 1.19.x AND 1.19.x-hidpi? Or is it always going to be a single combined package with hidpi and non-hidpi artifacts?

**Comment by slavfox** [comment]
@twelveeighty - no, it's always going to be a single, combined release. The reason why this latest one is 1.19.2-hidpi rather than 1.19.3 is because it only involved changes in the build toolchain, i.e. `cozette.otb` 1.19.2 is the same font, regardless of the suffix. I bump up the version number of the font if and only if I make any changes or additions to the font itself, and the releases get tagged with the font version.

**Comment by slavfox** [comment]
Done as of [v.1.19.3](https://github.com/slavfox/Cozette/releases/tag/v.1.19.3).
